services:
    david63.logconnections.listener:
        class: david63\logconnections\event\listener
        arguments:
            - '@david63.logconnections.main.controller'
        tags:
            - { name: event.listener }

    david63.logconnections.main.controller:
        class: david63\logconnections\controller\main_controller
        arguments:
            - '@config'		
            - '@log'
            - '@user'
            - '@auth'

    david63.logconnections.admin.controller:
        class: david63\logconnections\controller\admin_controller
        arguments:
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '@log'
            - '@language'
            - '@david63.logconnections.core.functions'

    david63.logconnections.core.functions:
        class: david63\logconnections\core\functions
        arguments:
            - '@ext.manager'
